name: Build Android App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython
    
    - name: Set up Android SDK environment
      run: |
        echo "export ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "export PATH=\$PATH:\$ANDROID_HOME/tools:\$ANDROID_HOME/platform-tools:\$ANDROID_HOME/build-tools/36.0.0" >> $GITHUB_ENV
    
    - name: Accept Android SDK licenses
      run: |
        yes | sdkmanager --licenses || true
        yes | sdkmanager --update || true
    
    - name: Install Build-Tools 36
      run: sdkmanager "build-tools;36.0.0"
    
    - name: Build with Buildozer
      run: buildozer -v android debug

    - name: Cache Android SDK
      uses: actions/cache@v3
      with:
        path: /usr/local/lib/android/sdk
        key: ${{ runner.os }}-android-sdk-${{ hashFiles('buildozer.spec') }}
