name: Build Android App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython
    
    - name: Set up Java with Android SDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'
        android: true
    
    - name: Setup Android SDK Path
      run: |
        echo "ANDROID_HOME=/opt/android/sdk" >> $GITHUB_ENV
        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
        echo "$ANDROID_HOME/build-tools/36.0.0" >> $GITHUB_PATH
    
    - name: Install Build-Tools and Accept Licenses
      run: |
        yes | sdkmanager --licenses || true
        yes | sdkmanager --update || true
        yes | sdkmanager "build-tools;36.0.0"
        yes | sdkmanager "platforms;android-33"
    
    - name: Build with Buildozer
      run: buildozer -v android debug
