name: Build Android App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          openjdk-11-jdk \
          zlib1g-dev \
          libncurses5-dev \
          libgdbm-dev \
          libnss3-dev \
          libssl-dev \
          libsqlite3-dev \
          libreadline-dev \
          libffi-dev \
          libbz2-dev \
          unzip \
          wget
    
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython
    
    - name: Setup Android SDK (Tsinghua Mirror)
      run: |
        mkdir -p ~/android-sdk
        cd ~/android-sdk
        # 使用清华镜像下载命令行工具
        wget https://mirrors.tuna.tsinghua.edu.cn/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
    
    - name: Accept licenses and install packages
      run: |
        # 设置清华镜像
        mkdir -p ~/.android
        echo '### User Sources for Android SDK Manager' > ~/.android/repositories.cfg
        echo 'count=0' >> ~/.android/repositories.cfg
        
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses --verbose
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
          --no_https \
          --proxy=http \
          --proxy_host=mirrors.tuna.tsinghua.edu.cn \
          --proxy_port=80 \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;34.0.0"
    
    - name: Build with Buildozer
      run: |
        # 设置国内PyPI镜像
        pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
        
        # 构建时使用国内镜像
        sed -i 's#https://dl.google.com#https://mirrors.tuna.tsinghua.edu.cn/git#g' buildozer.spec || true
        buildozer -v android debug
