name: Build Android App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          openjdk-17-jdk \
          zlib1g-dev \
          libncurses5-dev \
          libgdbm-dev \
          libnss3-dev \
          libssl-dev \
          libsqlite3-dev \
          libreadline-dev \
          libffi-dev \
          libbz2-dev \
          unzip \
          wget
    
    - name: Install Buildozer
      run: |
        sudo pip install --no-cache-dir Cython==0.29.36 buildozer
    
    - name: Setup Android SDK
      run: |
        mkdir -p ~/android-sdk
        cd ~/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_NDK_ROOT=$HOME/android-sdk/ndk-bundle" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
    
    - name: Accept ALL Android licenses
      run: |
        mkdir -p $ANDROID_HOME/licenses
        echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55\n84831b9409646a918e30573bab4c9c91346d8abd\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a63b6825ea9c5514f83c2829b004d1fee\n33b6a2b64607f17b3f689e6463ab23d242b4a6a5" > $ANDROID_HOME/licenses/android-sdk-license
        echo -e "\n601085b94cd77f0b54ff86406957099ebe79c4d6" > $ANDROID_HOME/licenses/android-sdk-preview-license
        echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-arm-dbt-license
        
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses --verbose
    
    - name: Install required packages
      run: |
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install \
          "platform-tools" \
          "platforms;android-34" \
          "build-tools;34.0.0" \
          "cmdline-tools;latest" \
          "ndk;25.2.9519653"
        
        # 创建 NDK 软链接
        mkdir -p $ANDROID_HOME/ndk-bundle
        ln -s $ANDROID_HOME/ndk/25.2.9519653/* $ANDROID_HOME/ndk-bundle/
        
        # 验证安装
        ls -la $ANDROID_HOME/build-tools/34.0.0
        $ANDROID_HOME/build-tools/34.0.0/aidl --version
    
    - name: Setup Android Environment
      run: |
        echo "$HOME/android-sdk/build-tools/34.0.0" >> $GITHUB_PATH
        
        # 验证路径
        echo "PATH: $PATH"
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
        echo "ANDROID_NDK_ROOT: $ANDROID_NDK_ROOT"
    
    - name: Configure Buildozer
      run: |
        sed -i 's/^android.build_tools_version =.*/android.build_tools_version = 34.0.0/' buildozer.spec
        sed -i 's/^android.sdk_version =.*/android.sdk_version = 34/' buildozer.spec
        sed -i 's/^android.accept_sdk_license =.*/android.accept_sdk_license = True/' buildozer.spec
        sed -i 's|^android.sdk_dir =.*|android.sdk_dir = '"$HOME"'/android-sdk|' buildozer.spec
        sed -i 's|^android.ndk_path =.*|android.ndk_path = '"$HOME"'/android-sdk/ndk-bundle|' buildozer.spec
        sed -i 's/^android.ignore_build_tools_version =.*/android.ignore_build_tools_version = False/' buildozer.spec
        
        # 打印配置用于调试
        cat buildozer.spec
    
    - name: Build with Buildozer
      run: |
        # 完全清理并重建
        rm -rf ~/.buildozer
        buildozer -v android debug
