name: Build Android App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          openjdk-17-jdk \
          zlib1g-dev \
          libncurses5-dev \
          libgdbm-dev \
          libnss3-dev \
          libssl-dev \
          libsqlite3-dev \
          libreadline-dev \
          libffi-dev \
          libbz2-dev \
          unzip \
          wget
    
    - name: Install Buildozer
      run: |
        sudo pip install --no-cache-dir Cython==0.29.36 buildozer
    
    - name: Setup Android SDK
      run: |
        mkdir -p ~/android-sdk
        cd ~/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
    
    - name: Accept licenses and install packages
      run: |
        # 确保许可文件被正确写入
        mkdir -p $ANDROID_HOME/licenses
        echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55\n84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-license
        echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e" > $ANDROID_HOME/licenses/android-sdk-preview-license
        
        # 强制安装所有可能需要的版本
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install \
          "platform-tools" \
          "platforms;android-34" \
          "build-tools;30.0.3" \
          "build-tools;31.0.0" \
          "build-tools;32.0.0" \
          "build-tools;33.0.2" \
          "build-tools;34.0.0" \
          "build-tools;36.0.0"
        
        # 验证安装
        ls $ANDROID_HOME/build-tools/*/aidl
    
    - name: Configure Buildozer
      run: |
        # 强制使用34.0.0版本并完全禁用自动检测
        echo -e "\n[buildozer]\nandroid.build_tools_version = 34.0.0" >> buildozer.spec
        sed -i 's/^android.accept_sdk_license = .*/android.accept_sdk_license = True/' buildozer.spec
        sed -i '/^android.sdk_dir = /d' buildozer.spec
        echo "android.sdk_dir = $HOME/android-sdk" >> buildozer.spec
        cat buildozer.spec
    
    - name: Build with Buildozer
      run: |
        # 强制清理并重建
        rm -rf ~/.buildozer
        buildozer -v android debug
